### ISSUE TITLE
生活三两事-静静 | 艾瑞可erik

### ISSUE THREAD

**Issue by erikaaron** [erikaaron/blogrepo.github.io#828]
https://erik.xyz/2019/09/29/life-sun-numbes-jingjing/ 

 从你朋友圈得知，你已经单身半年多了。我终于鼓起勇气从微信上和你互动。后来我们约了国庆你请客吃饭。我总感觉等到国庆怪怪的，前两天就立马约你晚上吃饭。那晚我们聊了很多，也很晚，各自回家。

**Comment by stayknight** [comment]
想的太多了，又太敏感，你这样很容易伤人伤己。感情的事，勉强不来。喜欢别人， 就大胆热情的去追；同时放豁达点，别人接不接受自己，都要有这个心理准备，坦然处之，不要因此心理大起大落。考虑问题和对待感情不要以自我为中心，每个人都有自己的生活重心，有自己在乎的人，而我们自己对于大多数人来说只是可有可无的边缘人物和过客而已，要学会认识到这一点并习惯。

**Comment by erikaaron** [comment]
> @stayknight
> 想的太多了，又太敏感，你这样很容易伤人伤己。感情的事，勉强不来。喜欢别人， 就大胆热情的去追；同时放豁达点，别人接不接受自己，都要有这个心理准备，坦然处之，不要因此心理大起大落。考虑问题和对待感情不要以自我为中心，每个人都有自己的生活重心，有自己在乎的人，而我们自己对于大多数人来说只是可有可无的边缘人物和过客而已，要学会认识到这一点并习惯。

谢谢！已经明白了。

**Comment by erikaaron** [comment]
> https://erik.xyz/2019/09/29/life-sun-numbes-jingjing/
> 
> 从你朋友圈得知，你已经单身半年多了。我终于鼓起勇气从微信上和你互动。后来我们约了国庆你请客吃饭。我总感觉等到国庆怪怪的，前两天就立马约你晚上吃饭。那晚我们聊了很多，也很晚，各自回家。
